---
title: "Data Management Project"
format: html
---

```{r}
#| message : false 
library(sf)
library(terra)
library(spData)
library(ggplot2)
library(rnaturalearth)
```

```{r}
world <- ne_download(returnclass = "sf")
```

```{r}
france <- world[world$NAME == "France", ]
```

```{r}
ggplot() +
  geom_sf(data = france) +
  theme_minimal() +
  ggtitle("Map of France") +
  coord_sf(xlim = c(-8, 10), ylim = c(40, 52))
```

```{r}
france2 <- ne_countries(country = "France", returnclass = "sf")
ggplot() +
  geom_sf(data = france2) +
  theme_minimal()
```

```{r}
library(sp)
world_sp = as(world, "Spatial") # from an sf object to sp
# sp functions ...
world_sf = st_as_sf(world_sp)   # from sp to sf
world_france <- world[world$NAME == "France", ]
france = st_union(world_france)
plot(france, reset = FALSE)
plot(france, add = TRUE, col = "red")
```
```{r}
library(rgdal)
#Carte de la France
france <- readOGR(dsn, 'france')
plot(france)
#Carte des régions de France
limite.regions <- unionSpatialPolygons(france, IDs = france@data$NOM_REGION)
plot(limite.regions)
```

```{r}
library(ggmap)
```

```{r}
library(ggmap)
us <- c(left = -125, bottom = 25.75, right = -67, top = 49)
map <- get_stadiamap(us, maptype = "toner-lite", zoom = 5)
ggmap(map)
```

